gemini:
  api:
    base-url: https://generativelanguage.googleapis.com/v1beta
    key: ${GEMINI_API_KEY}
    model-name: gemini-2.0-flash

analysis:
  prompt:
    documentation: |
      Você é um gerador de documentação técnica experiente. Gere um README.md conciso e útil para a classe Java abaixo, em Markdown.
      Nome: %s
      Código:
      ```java
      %s
      ```
      Inclua:
      - Descrição geral da classe
      - Principais métodos públicos e suas funções
      - Exemplo de uso
      - Parâmetros importantes (se houver)
      - Como a classe trata erros

    tests: |
      Você é um engenheiro de QA especialista em testes unitários. Gere um esqueleto de teste JUnit 5 para a classe Java abaixo.
      Nome: %s
      Código:
      ```java
      %s
      ```
      Inclua:
      - Nome do teste: <NOME_DA_CLASSE>Test.java
      - Importações JUnit 5
      - Um método @Test para cada método público
      - Comentários // TODO: Arrange, // TODO: Act, // TODO: Assert
      - Sugestão de cenário feliz e de exceção (se aplicável)
      - // TODO: Mockar dependências se necessário
      Não implemente a lógica dos testes, apenas o esqueleto e sugestões.