spring:
  profiles: prod
  application:
    name: DevApi
  datasource:
    url: ${DEVAPI_DB_URL}
    driver-class-name: ${DEVAPI_DB_DRIVER}
    username: ${DEVAPI_DB_USER}
    password: ${DEVAPI_DB_PASS}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 180000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.default_schema: public
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
logging:
  level:
    root: INFO
    com.eduhkbr.gemini.DevApi: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://seusite.com}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST}
cache:
  type: caffeine
  caffeine:
    spec: maximumSize=500,expireAfterAccess=600s
custom:
  feature-x-enabled: false
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  forward-headers-strategy: framework
