spring:
  application:
    name: DevApi
  datasource:
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${DEVAPI_DB_URL}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${DEVAPI_DB_USER}&password=${DEVAPI_DB_PASS}
    driver-class-name: {$DEVAPI_DB_DRIVER}
    hikari:
      jdbc-url: jdbc:postgresql:///${DB_NAME}
      username: ${DEVAPI_DB_USER}
      password: ${DEVAPI_DB_PASS}
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 180000
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DEVAPI_DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.default_schema: public
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
logging:
  level:
    root: INFO
    com.eduhkbr.gemini.DevApi: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST}
cache:
  type: caffeine
  caffeine:
    spec: maximumSize=500,expireAfterAccess=600s
custom:
  feature-x-enabled: false
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  forward-headers-strategy: framework
