spring:
  profiles: prod
  application:
    name: DevApi
  datasource:
    url: ${DEVAPI_DB_URL:jdbc:postgresql://localhost:5432/proddb}
    driver-class-name: ${DEVAPI_DB_DRIVER:org.postgresql.Driver}
    username: ${DEVAPI_DB_USER:produser}
    password: ${DEVAPI_DB_PASS:prodpass}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
logging:
  level:
    root: INFO
    com.eduhkbr.gemini.DevApi: WARN
cors:
  allowed-origins: 'https://seusite.com'
  allowed-methods: 'GET,POST'
cache:
  type: caffeine
custom:
  feature-x-enabled: false
