groups:
  - name: GeneralAlerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: 'critical'
        annotations:
          summary: "Inst칙ncia {{ $labels.instance }} est치 fora do ar"
          description: "O job {{ $labels.job }} na inst칙ncia {{ $labels.instance }} est치 fora do ar por mais de 1 minuto."